{
 "title": "CEF 儀表板 (Forti 版)",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "防火牆日誌圖表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "事件數量趨勢 - 依風險等級",
   "type": "graph",
   "description": "全部資料依 cef_severity 分類 cef_name: \"threat\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:157",
       "fake": true,
       "field": "cef_severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:158",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:155", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cef_name: /utm.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "事件數量趨勢 - 依風險類型",
   "type": "graph",
   "description": "全部資料依 cef_device_event_class_id 分類 cef_name: \"threat\"",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cef_device_event_class_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cef_name: /utm.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "每月份日誌收容數量趨勢圖",
   "type": "graph",
   "description": "每日 EPS 最大值統計 1h",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "EPS",
     "bucketAggs": [
      {
       "fake": true,
       "field": "log_time",
       "id": "3",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大阻擋目標主機",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dst.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "act: \"deny\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大阻擋來源主機",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "act: /deny.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大阻擋目標埠",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dpt.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "act: /deny.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大通過目標主機",
   "type": "graph",
   "description": "act: \"allow\"",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dst.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT act: \"deny\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大通過來源主機",
   "type": "graph",
   "description": "act: \"allow\"",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT act: \"deny\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大通過目標埠",
   "type": "graph",
   "description": "act: \"allow\"",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dpt.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT act: \"deny\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "每日通訊協定使用量統計趨勢圖",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TCP",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "proto: \"6\"",
     "timeField": "log_time"
    },
    {
     "alias": "UDP",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "proto: \"17\"",
     "timeField": "log_time"
    },
    {
     "alias": "ICMP",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "proto: \"1\"",
     "timeField": "log_time"
    },
    {
     "alias": "HIP",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "proto: \"139\"",
     "timeField": "log_time"
    },
    {
     "alias": "others",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(NOT proto: \"6\") AND (NOT proto: \"17\") AND (NOT proto: \"1\") AND (NOT proto: \"139\") AND proto: /.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "每月通訊協定使用量比例圖",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "TCP",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "proto: \"6\"",
     "timeField": "log_time"
    },
    {
     "alias": "UDP",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "proto: \"17\"",
     "timeField": "log_time"
    },
    {
     "alias": "ICMP",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "proto: \"1\"",
     "timeField": "log_time"
    },
    {
     "alias": "HIP",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "proto: \"139\"",
     "timeField": "log_time"
    },
    {
     "alias": "others",
     "bucketAggs": [
      { "field": "log_time", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(NOT proto: \"6\") AND (NOT proto: \"17\") AND (NOT proto: \"1\") AND (NOT proto: \"139\") AND proto: /.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "設備動作種類比例圖",
   "type": "grafana-piechart-panel",
   "description": "cef_name 是 threat, 依 act 分類",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "act.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cef_name: /utm.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "十大通報風險值比例圖",
   "type": "grafana-piechart-panel",
   "description": "十大通報風險值比例 (cef_name 是 THREAT, 依 cef_severity 分類)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cef_severity.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "src.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cef_name: /utm.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "疑似入侵成功比例",
   "type": "grafana-piechart-panel",
   "description": "疑似入侵成功之行為通報事件比例 (cef_name 是 THREAT 且 act 是 allow)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cef_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "log_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cef_name: /utm.*/ AND (NOT act: \"deny\")",
     "timeField": "log_time"
    }
   ]
  }
 ]
}