{
 "title": "CEF 儀表板 (PA 版)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "事件數量趨勢 - 依風險等級",
   "type": "graph",
   "description": "全部資料依 cef_severity 分類 cef_name: \"threat\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:317",
       "fake": true,
       "field": "cef_severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:318",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:315", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND cef_name: \"threat\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "事件數量趨勢 - 依風險類型",
   "type": "graph",
   "description": "全部資料依 cef_device_event_class_id 分類 cef_name: \"threat\"",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "cef_device_event_class_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:461",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:458", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND cef_name: \"threat\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "每月份日誌收容數量趨勢圖",
   "type": "graph",
   "description": "每日 EPS 最大值統計 1h",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "EPS",
     "bucketAggs": [
      {
       "$$hashKey": "object:366",
       "fake": true,
       "field": "log_time",
       "id": "3",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:364", "field": "select field", "id": "4", "type": "count" }
     ],
     "query": "_log_type: \"cef\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大阻擋目標主機",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:490",
       "fake": true,
       "field": "dst.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:491",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:488", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND act: /deny.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大阻擋來源主機",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:520",
       "fake": true,
       "field": "src.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:521",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:518", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND act: /deny.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大阻擋目標埠",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:550",
       "fake": true,
       "field": "dpt.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:551",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:548", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND act: /deny.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大通過目標主機",
   "type": "graph",
   "description": "act: \"allow\"",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:580",
       "fake": true,
       "field": "dst.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:581",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:578", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND act: /allow.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大通過來源主機",
   "type": "graph",
   "description": "act: \"allow\"",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:615",
       "fake": true,
       "field": "src.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:616",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:613", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND act: /allow.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "防火牆每月十大通過目標埠",
   "type": "graph",
   "description": "act: \"allow\"",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:656",
       "fake": true,
       "field": "dpt.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:657",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:654", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND act: /allow.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "每日通訊協定使用量統計趨勢圖",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:682",
       "fake": true,
       "field": "proto.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:683",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:680", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "每月通訊協定使用量比例圖",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:731",
       "fake": true,
       "field": "proto.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:732",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:729", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "疑似入侵成功比例",
   "type": "grafana-piechart-panel",
   "description": "疑似入侵成功之行為通報事件比例 (cef_name 是 THREAT 且 act 是 allow)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "疑似入侵成功次數",
     "bucketAggs": [
      {
       "$$hashKey": "object:780",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:778", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND cef_name:\"THREAT\" AND act:/allow.*/",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "十大通報風險值比例圖",
   "type": "grafana-piechart-panel",
   "description": "十大通報風險值比例 (cef_name 是 THREAT, 依 cef_severity 分類)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:814",
       "fake": true,
       "field": "cef_severity.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:815",
       "fake": true,
       "field": "src.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:816",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:812", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND cef_name: \"THREAT\"",
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "設備動作種類比例圖",
   "type": "grafana-piechart-panel",
   "description": "cef_name 是 threat, 依 act 分類",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:876",
       "fake": true,
       "field": "act.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:877",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:874", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_log_type: \"cef\" AND cef_name:\"threat\"",
     "timeField": "log_time"
    }
   ]
  }
 ]
}