{
 "title": "系統資源監控",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU 使用率",
   "type": "gauge",
   "description": "system.cpu.total.pct：The percentage of CPU time spent in states other than Idle and IOWait.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "CPU",
     "bucketAggs": [
      {
       "$$hashKey": "object:5541",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5539",
       "field": "system.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"cpu\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory 使用率",
   "type": "gauge",
   "description": "system.memory.used.pct：The percentage of used memory.",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "alias": "CPU",
     "bucketAggs": [
      {
       "$$hashKey": "object:5541",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5539",
       "field": "system.memory.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"memory\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory 總量",
   "type": "singlestat",
   "description": "system.memory.total：Total memory.",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "CPU",
     "bucketAggs": [
      {
       "$$hashKey": "object:5541",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5539",
       "field": "system.memory.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"memory\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk 使用率",
   "type": "gauge",
   "description": "system.filesystem.used.pct：The percentage of used disk space.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:5541",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5539",
       "field": "system.filesystem.total",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1446",
       "field": "system.filesystem.available",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:6003",
       "field": "system.filesystem.total",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "$$hashKey": "object:6010",
       "field": "system.filesystem.available",
       "hide": true,
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "$$hashKey": "object:6021",
       "field": "select field",
       "id": "7",
       "meta": {},
       "pipelineVariables": [
        { "$$hashKey": "object:6036", "name": "var1", "pipelineAgg": "1" },
        { "$$hashKey": "object:6041", "name": "var2", "pipelineAgg": "3" },
        { "$$hashKey": "object:6046", "name": "var3", "pipelineAgg": "5" },
        { "$$hashKey": "object:6051", "name": "var4", "pipelineAgg": "6" }
       ],
       "settings": {
        "script": "((params.var1 + params.var3) - (params.var2 + params.var4)) / (params.var1 + params.var3)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"filesystem\" AND (system.filesystem.mount_point: \"/hostfs/opt/Logs\" OR system.filesystem.mount_point: \"/hostfs\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk 總量",
   "type": "singlestat",
   "description": "system.filesystem.total：The total disk space in bytes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:5462",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:906",
       "field": "system.filesystem.total",
       "hide": true,
       "id": "3",
       "meta": {},
       "pipelineVariables": [
        { "$$hashKey": "object:5473", "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:5596",
       "field": "system.filesystem.total",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "$$hashKey": "object:5608",
       "field": "select field",
       "id": "5",
       "meta": {},
       "pipelineVariables": [
        { "$$hashKey": "object:5619", "name": "var1", "pipelineAgg": "3" },
        { "$$hashKey": "object:5624", "name": "var2", "pipelineAgg": "4" }
       ],
       "settings": { "script": "params.var1 + params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"filesystem\" AND (system.filesystem.mount_point: \"/hostfs/opt/Logs\" OR system.filesystem.mount_point: \"/hostfs\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory 剩餘量",
   "type": "singlestat",
   "description": "system.memory.free：The total amount of free memory in bytes. This value does not include memory consumed by system caches and buffers.",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "CPU",
     "bucketAggs": [
      {
       "$$hashKey": "object:5541",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5539",
       "field": "system.memory.free",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"memory\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk 剩餘量",
   "type": "singlestat",
   "description": "system.filesystem.free：The disk space available in bytes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:5541",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5539",
       "field": "system.filesystem.available",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:5824",
       "field": "system.filesystem.available",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "$$hashKey": "object:5832",
       "field": "select field",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "$$hashKey": "object:5847", "name": "var1", "pipelineAgg": "1" },
        { "$$hashKey": "object:5852", "name": "var2", "pipelineAgg": "3" }
       ],
       "settings": { "script": "params.var1 + params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"filesystem\" AND (system.filesystem.mount_point: \"/hostfs/opt/Logs\" OR system.filesystem.mount_point: \"/hostfs\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alert List",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1055",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1053", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU 使用率",
     "bucketAggs": [
      {
       "$$hashKey": "object:6352",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:6350",
       "field": "system.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"cpu\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory 使用率",
   "type": "graph",
   "description": "The percentage of used memory.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Memory 使用率",
     "bucketAggs": [
      {
       "$$hashKey": "object:5541",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5539",
       "field": "system.memory.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"memory\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk 使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Disk 使用率",
     "bucketAggs": [
      {
       "$$hashKey": "object:5541",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5539",
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"filesystem\" AND system.filesystem.mount_point: \"/hostfs\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In / Out (Bytes) per 10s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Outbound",
     "bucketAggs": [
      {
       "$$hashKey": "object:5032",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5030",
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:3112",
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"network\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Inbound",
     "bucketAggs": [
      {
       "$$hashKey": "object:5032",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5030",
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:2580",
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"network\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In / Out (Packets) per 10s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outbound",
     "bucketAggs": [
      {
       "$$hashKey": "object:5032",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5030",
       "field": "system.network.out.packets",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:3112",
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"network\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "inbound",
     "bucketAggs": [
      {
       "$$hashKey": "object:5032",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5030",
       "field": "system.network.in.packets",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:2580",
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "event.module: \"system\" AND metricset.name: \"network\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}