{
 "title": "入侵偵測告警",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters", "label": "查詢" }
  ]
 },
 "panels": [
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "告警量趨勢圖",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:231",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:229", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "告警總數",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:249",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:247", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "風險等級 (alert.severity)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:279",
       "fake": true,
       "field": "alert.severity",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:280",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:277", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "觸發規則的類別 (alert.category)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:305",
       "fake": true,
       "field": "alert.category.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:306",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:303", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "十大來源 IP (src_ip)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:335",
       "fake": true,
       "field": "src_ip.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:336",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:333", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "十大目標 IP (dest_ip)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:361",
       "fake": true,
       "field": "dest_ip.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:362",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:359", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "十大來源埠 (src_port)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:392",
       "fake": true,
       "field": "src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:393",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:390", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "十大目標埠 (dest_port)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:418",
       "fake": true,
       "field": "dest_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:419",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:416", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "封包的處理方式 (alert.action)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:444",
       "fake": true,
       "field": "alert.action.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:445",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:442", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "通訊協定 (proto)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:470",
       "fake": true,
       "field": "proto.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:471",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:468", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "觸發規則的訊息 (alert.signature)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:496",
       "fake": true,
       "field": "alert.signature.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:497",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:494", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "觸發規則的 ID (alert.signature_id)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:496",
       "fake": true,
       "field": "alert.signature_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:497",
       "field": "log_time",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:494", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "log_time"
    }
   ]
  },
  {
   "title": "近一萬筆資料",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:520",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 10000 },
       "type": "raw_document"
      }
     ],
     "timeField": "log_time"
    }
   ]
  }
 ]
}